/*
 * HomeConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const CHANGE_USERNAME = 'boilerplate/Home/CHANGE_USERNAME';

export const mocData = [
  {
    id: 563,
    name: 'test.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 564,
    name: 'demo_test.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo1_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 565,
    name: 'jhvhjkgvhjgvhjvg.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart4',
    ccprecipelocation: 'Demo_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 566,
    name: 'nbvbvbvhhvvc.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart3',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart3',
    ccprecipelocation: 'Demo1_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 567,
    name: 'kjhgkjhgjghjhgj.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart2',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart2',
    ccprecipelocation: 'Demo_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 568,
    name: 'sghvdjhgvadcasd.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart1',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart1',
    ccprecipelocation: 'Demo1_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 569,
    name: 'ughkasjydkjcvakjshd.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo_1553284531600.opn',
    ccpProcedureId: '561',
  },
  {
    id: 570,
    name: 'tuyrdurdtdur.opn',
    status: 'Draft',
    version: 'V1',
    author: 'merckservice',
    modifiedDate: 1576134122000,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo1_1553284531600.opn',
    ccpProcedureId: '561',
  },
];
export const deviceList = [
  {
    id: 66,
    deviceID: '6001',
    version: '045',
    location: 'Lab 6A',
    lastCalibration: 'Apr 23, 2019 11:04:00 PM',
    configuration:
      'Has this customization \nHas that\nThis portion is to be defined. Today its just a free form area',
    manufacturer: 'Merck',
    installation_date: 'Jul 14, 2015 11:00:00 PM',
    device_status: 'connected',
    device_type: 'Bioreactor',
    onboard: 'true',
    port: 8089,
    device_name: 'Bioreactor Line 1',
    recipe_name: 'Acme-BioProcess-Recipe-1.2',
    recipe_status: 'Running',
    batch_id: 'auDMJ-BJz9R-4c6nx-DcYU4',
    software_version: '1.0',
    model: 'XMO4',
    order_number: 0,
  },
  {
    id: 83,
    deviceID: '12345',
    ccpIp: '141.247.210.86',
    location: '',
    device_type: 'Chromatography',
    onboard: 'true',
    port: 8089,
    device_name: '12345',
    order_number: 0,
  },
];
export const opnData = [
  {
    id: 2094,
    name: 'Demo_1555003999576.opn',
    status: 'Draft1',
    version: 'V1',
    author: 'falconmerck',
    modifiedDate: 1555000399608,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart1',
    ccprecipelocation: 'Demo_1555003999576.opn',
    ccpProcedureId: '0',
  },
  {
    id: 2095,
    name: 'Demo1_1555003999576.opn',
    status: 'Draft2',
    version: 'V1',
    author: 'falconuser',
    modifiedDate: 1555000399623,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP1',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo1_1555003999576.opn',
    ccpProcedureId: '0',
  },
  {
    id: 2095,
    name: 'Demo1_1555003999576.opn',
    status: 'Draft',
    version: 'V1',
    author: 'falconuser',
    modifiedDate: 1555000399623,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP2',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'Demo1_1555003999576.opn',
    ccpProcedureId: '0',
  },
  {
    id: 2098,
    name: 'CCPRecipe_1555007482676.opn',
    status: 'Draft',
    version: 'V1',
    author: 'falconuser',
    modifiedDate: 1555003882743,
    recipe: 'smart',
    deviceId: '3003',
    deviceUoPVersion: 'CCP04',
    deviceUoP: 'CCP',
    deviceSubFamily: 'Smart XMO',
    deviceFamily: 'smart',
    ccprecipelocation: 'CCPRecipe_1555007482676.opn',
    ccpProcedureId: '0',
  },
];
